namespace WowClassicEraItems.Repository.Items;

/// <summary>
/// Persistence entity mapped to the "Items" table. Stores the raw JSON
/// payload returned by the Blizzard item API, with a handful of computed
/// columns projected out of it for querying/indexing.
/// </summary>
public class ItemRecord
{
    /// <summary>Surrogate primary key, generated by the database.</summary>
    public int Id { get; set; }

    /// <summary>The Blizzard item id (data.id) - an external reference, not our primary key.</summary>
    public int BlizzardItemId { get; set; }

    /// <summary>Raw JSON of the "data" node from the Blizzard item API response.</summary>
    public string RawJson { get; set; } = string.Empty;

    /// <summary>When this row was inserted.</summary>
    public DateTime Created { get; set; }

    /// <summary>
    /// When this snapshot was fetched. Combined with <see cref="BlizzardItemId"/> this
    /// forms the unique key, so re-importing an item always inserts a new row (a new
    /// snapshot in time) instead of requiring an update/upsert.
    /// </summary>
    public DateTime Updated { get; set; }

    /// <summary>Computed column: data.name.en_US. Set by SQL Server, not by application code.</summary>
    public string? Name { get; private set; }

    /// <summary>
    /// Resolved icon URL from Blizzard's item media endpoint. Null until it's
    /// been looked up (lazily, on first read of this item) and persisted here
    /// so subsequent reads don't need to call Blizzard again.
    /// </summary>
    public string? Icon { get; set; }
}
