// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WowClassicEraItems.Repository;

#nullable disable

namespace WowClassicEraItems.Repository.Migrations
{
    [DbContext(typeof(WowClassicEraItemsDbContext))]
    [Migration("20260917125400_AddCreatedUpdatedColumns")]
    partial class AddCreatedUpdatedColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WowClassicEraItems.Repository.Items.ItemRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlizzardItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(50)")
                        .HasComputedColumnSql("CAST(JSON_VALUE([RawJson], '$.media.id') AS NVARCHAR(50))", true);

                    b.Property<string>("Name")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(400)")
                        .HasComputedColumnSql("JSON_VALUE([RawJson], '$.name.en_US')", true);

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlizzardItemId", "Updated")
                        .IsUnique();

                    b.ToTable("Items", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
